[build]
builder = "dockerfile"

[deploy]
startCommand = "python manage.py migrate && gunicorn glamstore.wsgi:application --bind 0.0.0.0:8000"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
