services:
  - type: web
    name: glamstore
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn glamstore.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: PYTHONUNBUFFERED
        value: true
